application:
  timezone: Asia/Kolkata
  debug: true
auth:
  expiryduration: 3600
  expirylongduration: 2592000
  secretkey: random30293339393securedkey
restserver:
  address: localhost
  port: 8080
database:
  driver: mysql
  host: localhost
  port: 3306
  username: owner
  password: owner
  dbname: wms
  logquery: true